"use client"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sparkles, Copy, Check } from "lucide-react"

export default function LatexToolPage() {
  const [inputText, setInputText] = useState("")
  const [taskType, setTaskType] = useState("improve")
  const [outputText, setOutputText] = useState("")
  const [isProcessing, setIsProcessing] = useState(false)
  const [copied, setCopied] = useState(false)

  const handleProcess = () => {
    setIsProcessing(true)
    // Simulate AI processing
    setTimeout(() => {
      setOutputText(
        `\\documentclass{article}\n\\usepackage{amsmath}\n\\usepackage{graphicx}\n\n\\begin{document}\n\n\\title{${inputText || "Your Paper Title"}}\n\\author{Author Name}\n\\date{\\today}\n\\maketitle\n\n\\begin{abstract}\nThis is a sample abstract generated by the AI LaTeX assistant.\n\\end{abstract}\n\n\\section{Introduction}\nYour introduction text here.\n\n\\end{document}`,
      )
      setIsProcessing(false)
    }, 1500)
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(outputText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">AI LaTeX Assistant</h1>
        <p className="text-muted-foreground mt-1">Get help writing, improving, and debugging your LaTeX documents</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Input Panel */}
        <div className="lg:col-span-2 space-y-4">
          <Card className="p-6">
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="task">Task Type</Label>
                <Select value={taskType} onValueChange={setTaskType}>
                  <SelectTrigger id="task">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="improve">Improve Writing</SelectItem>
                    <SelectItem value="debug">Debug Errors</SelectItem>
                    <SelectItem value="format">Format Document</SelectItem>
                    <SelectItem value="generate">Generate Structure</SelectItem>
                    <SelectItem value="convert">Convert to LaTeX</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="input">Input Text</Label>
                <Textarea
                  id="input"
                  placeholder="Enter your text, LaTeX code, or description..."
                  className="min-h-[400px] font-mono text-sm"
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                />
              </div>

              <Button className="w-full" size="lg" onClick={handleProcess} disabled={isProcessing || !inputText}>
                {isProcessing ? (
                  <>Processing...</>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5 mr-2" />
                    Process with AI
                  </>
                )}
              </Button>
            </div>
          </Card>

          <Card className="p-6">
            <h3 className="font-semibold mb-3">Common Tasks</h3>
            <div className="space-y-2 text-sm text-muted-foreground">
              <p>• Convert plain text to LaTeX format</p>
              <p>• Fix compilation errors</p>
              <p>• Improve academic writing style</p>
              <p>• Generate document structure</p>
              <p>• Format equations and tables</p>
            </div>
          </Card>
        </div>

        {/* Output Panel */}
        <div className="lg:col-span-3 space-y-4">
          <Card className="p-6">
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label>Generated LaTeX</Label>
                {outputText && (
                  <Button variant="outline" size="sm" onClick={handleCopy}>
                    {copied ? (
                      <>
                        <Check className="w-4 h-4 mr-2" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4 mr-2" />
                        Copy
                      </>
                    )}
                  </Button>
                )}
              </div>
              <Textarea
                readOnly
                placeholder="AI-generated LaTeX will appear here..."
                className="min-h-[400px] font-mono text-sm"
                value={outputText}
              />
            </div>
          </Card>

          <Card className="p-6">
            <h3 className="font-semibold mb-3">Preview</h3>
            <div className="bg-muted rounded-lg p-6 min-h-[200px] flex items-center justify-center">
              <p className="text-sm text-muted-foreground">
                {outputText ? "LaTeX preview would render here" : "Process input to see preview"}
              </p>
            </div>
          </Card>
        </div>
      </div>
    </div>
  )
}
